#!/bin/bash
#
# https://stackoverflow.com/questions/3207728/retaining-file-permissions-with-git
# But we store ONLY dir permissions


SELF_DIR=`git rev-parse --show-toplevel`
DATABASE=$SELF_DIR/config/.permissions

echo -n "Restoring permissions..."

IFS_OLD=$IFS; IFS=$'\n'
while read -r LINE || [[ -n "$LINE" ]];
do
   ITEM=`echo $LINE | cut -d ";" -f 1`
   PERMISSIONS=`echo $LINE | cut -d ";" -f 2`

   # Set the file/directory permissions
   chmod $PERMISSIONS $ITEM

done < $DATABASE
IFS=$IFS_OLD

echo "OK"

exit 0